### ISSUE TITLE
Параметры в MC_SixStep_param.h

### ISSUE THREAD

**Issue by jst-r** [jst-r/SMKB_UKOS#1]
Когда добавлял изменение направления вращения в STM32CubeExpansion_SPN7_V1.1.0/Projects/Multi/Examples/MotorControl/Inc/MC_SixStep_param.h у меня были другие константы, чекните что там должно быть. 
[https://github.com/jst-r/SMKB_UKOS/commit/f4bf5a8d040615f43a9bf61b32c7e83c0521086f](url на коммит)

**Comment by Marcusfur** [comment]
Done

**Comment by Marcusfur** [comment]
Done
